#if !defined(AFX_RECORDSET4MSHFLEXGRID_H__B9ABD464_2C0F_4AB3_898E_34A0A2D64744__INCLUDED_)
#define AFX_RECORDSET4MSHFLEXGRID_H__B9ABD464_2C0F_4AB3_898E_34A0A2D64744__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRecordset4MSHFlexGrid wrapper class

class CRecordset4MSHFlexGrid : public COleDispatchDriver
{
public:
	CRecordset4MSHFlexGrid() {}		// Calls COleDispatchDriver default constructor
	CRecordset4MSHFlexGrid(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRecordset4MSHFlexGrid(const CRecordset4MSHFlexGrid& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RECORDSET4MSHFLEXGRID_H__B9ABD464_2C0F_4AB3_898E_34A0A2D64744__INCLUDED_)
